// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121055610_Adding-Gateway-ID")]
    partial class AddingGatewayID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Entities.ApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Api")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeviceConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceConfigurationId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DeviceConfiguration", b =>
                {
                    b.Property<Guid>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollIntervalMs")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolSettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigurationId");

                    b.ToTable("DeviceConfigurations");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DeviceSlave", b =>
                {
                    b.Property<Guid>("deviceSlaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<int>("slaveIndex")
                        .HasColumnType("int");

                    b.HasKey("deviceSlaveId");

                    b.HasIndex("DeviceId", "slaveIndex")
                        .IsUnique();

                    b.ToTable("DeviceSlaves");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Register", b =>
                {
                    b.Property<Guid>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ByteOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<int>("RegisterAddress")
                        .HasColumnType("int");

                    b.Property<int>("RegisterLength")
                        .HasColumnType("int");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WordSwap")
                        .HasColumnType("bit");

                    b.Property<Guid>("deviceSlaveId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegisterId");

                    b.HasIndex("deviceSlaveId", "RegisterAddress")
                        .IsUnique();

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Device", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.DeviceConfiguration", "DeviceConfiguration")
                        .WithMany()
                        .HasForeignKey("DeviceConfigurationId");

                    b.Navigation("DeviceConfiguration");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DeviceSlave", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Device", "Device")
                        .WithMany("DeviceSlave")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Register", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.DeviceSlave", "DeviceSlave")
                        .WithMany("Registers")
                        .HasForeignKey("deviceSlaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceSlave");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Device", b =>
                {
                    b.Navigation("DeviceSlave");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.DeviceSlave", b =>
                {
                    b.Navigation("Registers");
                });
#pragma warning restore 612, 618
        }
    }
}
